use_ddp: False
port:

batch_size: 6

resume: 
work_dir: ./result
max_iter: 800000
seed: 2
g_lr: 2e-4
d_lr: 1e-3
ac_lr: 2e-4
n_workers: 2
adam_betas: [0.0, 0.9]
init: kaiming

language: th
decomposition: /content/th_decom.json
primals: /content/th_primal.json

dset_aug:
  normalize: True
  random_affine: True

dset:
  train:
    data_dir: /content/fonts_to_train
    n_in_s: 3
    n_in_c: 3
  val:
    data_dir: /content/fonts_to_val
    n_ref: 4
    source_font: /content/fonts_to_train/TH-Sarabun-New-Regular.ttf
  test:
    data_dir: /content/fonts_to_val
    source_font: /content/fonts_to_train/TH-Sarabun-New-Regular.ttf
    gen_chars_file: /content/drive/MyDrive/Year4/cv/mxfont/data/th_gen.json

# model
C: 32
g_args:
  style_enc:
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  experts:
    n_experts: 6
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  emb_num: 2
  dec:
    norm: in
    activ: relu
    pad_type: zero
    out: sigmoid
d_args:
  w_norm: spectral
  activ: relu
  gap_activ: relu
  pad_type: zero
  res_scale_var: False
ac_args:
  norm: in
  activ: relu
  pad_type: zero
  conv_dropout: 0.3
  clf_dropout: 0.2

# losses
pixel_loss_type: l1
pixel_w: 0.1
gan_w: 1.0
fm_layers: all
fm_w: 1.0
ac_w: 1.0
ac_gen_w: 1.0
ac_cross_w: 1.0
indp_exp_w: 1.0
indp_fact_w: 1.0

# etc
save: all-last
print_freq: 50
val_freq: 10000
save_freq: 5000
tb_freq: 100
